name: Auto approve

on: 
  pull_request:
    types: [opened, reopened, ready_for_review, review_requested]

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: Bohdan-Tereta/auto-approve-action-by-reviewer-name@v2
        with:
          review-message: "Auto approved automated PR"
          reviewer: "Team1"
          github-token: "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"